tags:
  - Tasks
summary: Get all tasks
operationId: getTasks
description: Retrieves all tasks for the authenticated user
security:
  - bearerAuth: []
responses:
  '200':
    description: Successfully found tasks!
    content:
      application/json:
        schema:
          type: object
          properties:
            status:
              type: integer
              example: 200
            message:
              type: string
              example: Successfully found tasks!
            data:
              type: array
              items:
                $ref: '../../../components/schemas/task.yaml'
  '401':
    $ref: '../../../components/responses/401.yaml'
