get:
  summary: Get all tasks
  operationId: getTasks
  tags:
    - Tasks
  description: Retrieves all tasks for the authenticated user.
  security:
    - bearerAuth: []
  responses:
    '200':
      description: Tasks retrieved successfully
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              message:
                type: string
                example: Successfully found tasks!
              data:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    '401':
      $ref: '#/components/responses/Unauthorized'
