post:
  summary: Create a new task
  operationId: createTask
  tags:
    - Tasks
  description: Creates a new task for the authenticated user.
  security:
    - bearerAuth: []
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
          required:
            - title
            - date
          properties:
            title:
              type: string
              example: Buy groceries
            date:
              type: string
              format: date
              example: '2025-09-18'
  responses:
    '201':
      description: Task created successfully
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Task'
    '401':
      $ref: '#/components/responses/Unauthorized'
